- wercker.yml
> add: werckerのチェックの通知と無駄なフェーズを削除

- design/constant.go
- design/cors.go
- design/design.go
- design/security.go
> goaのデザインベース作成

- Makefile
> add: 依存パッケージの追加

- Makefile
- design/api_definition.go
- design/resource/events.go
- design/resource/favorites.go
- server/main.go
フロントとサーバーのエンドポイントが被っていた。
また、バイナリデータが大きすぎたので修正した。
> エンドポイントの指定が間違っていたので修正

- mymiddleware/auth.go
> add: ベースとなるミドルウェアの作成

- .gitignore
- Makefile
- design/api_definition.go
- server/app.yaml
- server/dev.yaml.tmpl
- server/dev.yaml.tmpl2
- server/env.yaml.dev
- server/env.yaml.dev.nosec
- server/env.yaml.production
- server/env.yaml.staging
- wercker.yml
> update: 環境別の設定ファイルを用意し、swaggerのHOSTを動的に変えるようにした

- Makefile
makeコマンドでのdeployが若干危険だったので、書き換え。
> add: デプロイコマンドにyamlの設定を上書きすフェーズを追加する

- controller/events.go
- controller/favorites.go
- design/media/event.go
- design/media/user.go
- design/resource/events.go
- design/resource/favorites.go
- mock/value.go
- util/helper.go
- util/helper_test.go
> add: mockの実装

- lint_config.json
- model/api.go
- model/d_events.go
- model/d_user_event_favorites.go
- model/d_user_event_reads.go
- model/d_users.go
> Datastoreのベース作成

- model/s_events.go
close https://github.com/enow-dev/enow/issues/24
> add: search api model

- design/media/event.go
- design/resource/events.go
> fix: param naming

- server/env.yaml.dev
- server/env.yaml.dev.nosec
- server/env.yaml.production
> update: env naming

- .envrc
- Makefile
- config/api.go
- config/api.yaml.tmpl
- config/api_test.go
- controller/cron.go
- design/api_definition.go
- design/constant/constant.go
- design/cors.go
- design/resource/cron.go
- design/security.go
- fetch/paser.go
- server/env.yaml.staging
- server/main.go
> APIフェッチのためのベース作成

- front/src/Actions/Events.js
- front/src/Components/Events.js
- front/src/Reducers/Events.js
> add: 続きを読み込むを実装

- .gitignore
- Gopkg.lock
- Makefile
- config/api.go
- config/api.yaml.tmpl
- config/api_test.go
- controller/cron.go
- design/constant/constant.go
- design/resource/cron.go
- design/security.go
- fetch/paser.go
- model/api.go
- model/api_paser.go
- model/d_events.go
- mymiddleware/auth.go
- server/cron.yaml
- server/main.go
- util/helper.go
- util/storage.go
> イベント情報をフェッチするロジック実装

- Makefile
- wercker.yml
> Makefileの更新

- Makefile
- controller/cron.go
- model/d_events.go
- model/s_events.go
> add: データを格納するロジックが出来た

- controller/events.go
- design/api_definition.go
- design/media/event.go
- design/resource/events.go
- model/s_events.go
> イベント一覧に実際にクエリを投げて取得する

- Makefile
- config/api.yaml.tmpl
> APIを使う上に必要なコンフィグのフォーマットを更新する

- front/package.json
- front/src/Components/Events.js
> 検索ボックスをついてくるように実装。細かい調整はまたこんどする。

- Gopkg.lock
- controller/cron.go
- controller/events.go
- controller/favorites.go
- design/media/event.go
- design/resource/favorites.go
- model/d_events.go
- model/d_user_event_favorites.go
- model/d_user_event_reads.go
- model/d_users.go
- model/s_events.go
> add: イベント情報を1件取得する処理

- front/src/Components/Events.js
> fix:検索ボックスのstickrをぬるぬるにした

- controller/favorites.go
- design/media/event.go
- design/resource/events.go
- design/resource/favorites.go
- model/d_events.go
- model/d_user_event_favorites.go
- model/d_users.go
- mymiddleware/auth.go
- server/app.yaml
- util/context.go
> お気に入り追加の動きを追加

- front/src/Actions/Error.js
- front/src/Actions/Event.js
- front/src/Components/EventDetail.js
- front/src/Components/Home.js
- front/src/Constants/ActionTypes.js
- front/src/Reducers/Error.js
- front/src/Reducers/index.js
> fix: レスポンスコードによってホームページにリダイレクトするようにした

- front/package.json
> update: mui package

- controller/cron.go
- controller/events.go
- model/d_events.go
- model/d_search_events_log.go
- model/s_events.go
- util/helper.go
>  	add: 検索用Indexを自動生成して、動的に切り替えるようにした

- Gopkg.lock
- Gopkg.toml
- controller/auth.go
- design/media/session.go
- design/resource/oauth.go
- server/main.go
- server/public/login.html
> OAuth2の実装に必要なベースを作成

- Gopkg.lock
- controller/cron.go
- util/link.go
> fix: search API, Link Header

- controller/events.go
- design/resource/events.go
> add: 検索数を返すAPI

- controller/events.go
- design/api_definition.go
> add: イベント検索の結果一覧に検索ヒット数を返すようにした

- Gopkg.lock
- Gopkg.toml
- controller/auth.go
- design/media/session.go
- model/d_users.go
- util/cipher.go
> add: oauthでのユーザー作成

- controller/auth.go
- design/media/session.go
- model/d_users.go
> update: oauth時に生成するTokenがコンフリクトする可能生があるのでチェックするようにした

- controller/events.go
- model/d_user_event_reads.go
- mymiddleware/auth.go
- server/public/login.html
> add: tokenからユーザー紐付けと既読情報記録

- controller/favorites.go
- design/api_definition.go
- design/constant/constant.go
- design/resource/events.go
- design/security.go
- model/d_events.go
- model/d_user_event_favorites.go
- mymiddleware/auth.go
- server/main.go
> お気に入りリストとGuest用ミドルウェア

- front/src/Actions/Aouth.js
- front/src/Components/Header.js
- front/src/Reducers/Aouth.js
> fix: header avatar実装とログインアクションUIを変更

- controller/cron.go
- controller/events.go
- fetch/paser.go
- model/api_paser.go
- model/d_search_events_log.go
- model/d_user_event_favorites.go
- model/d_user_event_reads.go
- model/d_users.go
- model/s_events.go
- server/app.yaml
- server/cron.yaml
- util/helper.go
> add: 検索に既読除外機能追加

- front/src/Actions/Aouth.js
- front/src/Actions/Events.js
- front/src/App.js
- front/src/Components/Events.js
- front/src/Components/Header.js
- front/src/Components/Home.js
- front/src/Reducers/Aouth.js
> fix: 検索クエリ発行

- front/package.json
- front/src/Actions/Aouth.js
- front/src/Components/Header.js
- front/src/Constants/ActionTypes.js
- front/src/Reducers/Aouth.js
- server/index.yaml
> fix: ログイン情報をクッキーに保持

- front/src/Actions/Events.js
- front/src/Components/Home.js
> fix: 検索クエリに都道府県対応

- front/src/Actions/Aouth.js
- front/src/Actions/Event.js
- front/src/Actions/Events.js
- front/src/Utils/UrlScheme.js
> fix: 環境別urlをモデュール化

- front/src/Components/EventBox.js
- front/src/Components/Events.js
- front/src/Components/EventsTab.js
- front/src/Components/Header.js
- front/src/Components/Home.js
- front/src/Components/SearchBox.js
> fix: console error

- front/src/Components/Header.js
- front/src/Utils/AouthClientID.js
> fix: 軽微な修正、ヘッダーに環境変数を表示

- front/src/Components/Header.js
> fix: 軽微な修正

- front/src/Actions/SearchStash.js
- front/src/Components/Home.js
- front/src/Components/PrefMenu.js
- front/src/Components/SearchBox.js
- front/src/Constants/ActionTypes.js
- front/src/Reducers/SearchStash.js
- front/src/Reducers/index.js
> fix: 検索した状態を維持する。クッキー未対応

- front/src/Actions/SearchStash.js
- front/src/Components/Header.js
> fix: 検索状態をCookieに保持

- front/src/Components/EventBox.js
- front/src/Reducers/Events.js
> fix: place -> area

- controller/cron.go
- model/d_events.go
> add: structのコピーするメソッド

- front/src/Components/Home.js
> fix: slot　エフェクトがしょぼい

- front/src/Components/Events.js
close #145
いま、お気に入りボタンの色はまだ反映していない（お気に入りはできる）。
events APIのis_favoriteは動作させない？
> fix: favorite list

- controller/cron.go
- controller/events.go
- design/media/event.go
- design/resource/events.go
- model/d_user_event_favorites.go
- model/d_user_event_reads.go
- model/s_events.go
- mymiddleware/auth.go
close https://github.com/enow-dev/enow/issues/163
> add: 既読とお気に入りの表示

- front/src/Components/EventBox.js
- front/src/Reducers/Events/Event.js
- front/src/Reducers/Events/Favorite.js
- front/src/Reducers/Events/index.js
> fix: favorite button

- design/cors.go
> add: Access-Control-Expose-Headers

- front/src/App.js
> fix: 開発ように404を外す。

- front/package.json
- front/src/Actions/Events.js
- front/src/Components/Events.js
- front/src/Reducers/Events/index.js
> fix: 続きを読み込むとresponse linkの連携

- front/package.json
- front/src/Components/Home.js
- front/src/index.js
> fix: パッケージアップデートとレスポンシブの対応ベース

- Gopkg.toml
- config/oauth.go
- config/oauth.yaml.tmpl
- controller/auth.go
- design/resource/auth.go
- model/d_users.go
> add: Facebook OAuth2

- model/d_events.go
- model/s_events.go
> fix: tagが空の時に空配列を入れるようにした

- controller/events.go
- design/resource/events.go
- model/s_events.go
> add: 日付ソート、日付範囲指定

- front/src/Actions/Events.js
- front/src/Actions/FavoriteEvents.js
- front/src/Components/Events.js
- front/src/Constants/ActionTypes.js
- front/src/Reducers/Events/index.js
> fix: お気に入りリストを/api/events/self/favoritesから取得する。

- controller/events.go
- controller/favorites.go
- design/api_definition.go
- design/constant/constant.go
- design/resource/favorites.go
- model/d_user_event_favorites.go
- util/link.go
close #201 
close #205 
close #206
> お気に入りリスト周りの対応

- front/src/Actions/Aouth.js
> fix: payload

- controller/auth.go
- controller/events.go
- design/constant/constant.go
> add: #222 events

- front/src/Actions/Aouth.js
- front/src/Constants/ActionTypes.js
- front/src/Reducers/Aouth.js
> fix: bug修正

- front/src/Actions/Aouth.js
> fix: axiosの仕様に合わせる

- front/src/Actions/Events.js
- front/src/Views/Pages/Events/Web.js
- front/src/Views/Pages/Events/index.js
> fix: 不要な行の削除とuiの改修

- front/src/Actions/OAuth.js
> update: OAuth2 redirect URL
